[package]
name = "freegamrust"
version = "0.1.0"
authors = ["Aleksa Ognjanovic <alexa.ognjanovic@protonmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
xosd-rs = "0.2.0"
reqwest = "*"
